services:
  db_pg:
    image: postgres:17.3-alpine3.21
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/timezone:/etc/timezone:ro
      - ./data/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Moscow
    ports:
      - "5432:5432"