# Generated by Django 5.1.6 on 2025-02-18 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=500)),
                ('note_create_date', models.DateTimeField(auto_now_add=True)),
                ('note_notify_start', models.DateTimeField(blank=True, null=True)),
                ('note_notify_gap', models.DurationField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
